# Generated by Django 5.1.7 on 2025-04-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=255)),
                ('date_given', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
