# Generated by Django 5.1.7 on 2025-04-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancyjournal',
            name='mood',
            field=models.CharField(blank=True, choices=[('Happy', 'Happy'), ('Anxious', 'Anxious'), ('Tired', 'Tired'), ('Excited', 'Excited')], max_length=20, null=True),
        ),
    ]
