name: motherhood_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.7
  url_launcher: ^6.1.14 
  cupertino_icons: ^1.0.2
  provider: ^6.1.0
  dio: ^5.4.0  
  shared_preferences: ^2.2.2  
  flutter_local_notifications: ^16.1.0  
  firebase_core: ^3.12.1 
  firebase_messaging: ^15.2.4 
  firebase_storage: ^12.4.5
  intl: ^0.19.0  
  json_serializable: ^6.7.1  
  google_fonts: ^6.2.1  
  fl_chart: ^0.70.2
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_animate: ^4.2.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ✅ Add your asset path here
  assets:
    - assets/default_profile.png
