// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApsoudu6hQxvqapTQ7cE-IwrPTSxlv76s',
    appId: '1:216557505110:web:538c2b5e3bb6757c0849f7',
    messagingSenderId: '216557505110',
    projectId: 'achiever-2e982',
    authDomain: 'achiever-2e982.firebaseapp.com',
    storageBucket: 'achiever-2e982.firebasestorage.app',
    measurementId: 'G-3BY4HW7QHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAPtK-KHAqyRqwYnm-W6ovTOx_o9er0IU',
    appId: '1:216557505110:android:6bd18b120b50e59e0849f7',
    messagingSenderId: '216557505110',
    projectId: 'achiever-2e982',
    storageBucket: 'achiever-2e982.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC96aOupvHN04NlPSu2uKnjSz0WIzX6MvY',
    appId: '1:216557505110:ios:288e3dffeee010690849f7',
    messagingSenderId: '216557505110',
    projectId: 'achiever-2e982',
    storageBucket: 'achiever-2e982.firebasestorage.app',
    iosBundleId: 'com.example.motherhoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC96aOupvHN04NlPSu2uKnjSz0WIzX6MvY',
    appId: '1:216557505110:ios:288e3dffeee010690849f7',
    messagingSenderId: '216557505110',
    projectId: 'achiever-2e982',
    storageBucket: 'achiever-2e982.firebasestorage.app',
    iosBundleId: 'com.example.motherhoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApsoudu6hQxvqapTQ7cE-IwrPTSxlv76s',
    appId: '1:216557505110:web:88a583c0f03e99320849f7',
    messagingSenderId: '216557505110',
    projectId: 'achiever-2e982',
    authDomain: 'achiever-2e982.firebaseapp.com',
    storageBucket: 'achiever-2e982.firebasestorage.app',
    measurementId: 'G-DVC330GXT1',
  );
}
